spring:
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      token: roottoken
  datasource:
    username: postgres
    password: qwerty
    url: jdbc:postgresql://localhost:5434/hackathon_db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  application:
    name: hackathon-write-service
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
server:
  port: 0

